/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  2619
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.interq.or.jp"
#define VERSION_DATE   "Thu Jul 12 14:34:00 2012"
#define VERSION_STRING "lundman@shinken.interq.or.jp build 2619 (Thu Jul 12 14:34:00 2012)"

/* Lundtastic services */
