/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  2629
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.interq.or.jp"
#define VERSION_DATE   "Thu Sep 27 11:34:45 2012"
#define VERSION_STRING "lundman@shinken.interq.or.jp build 2629 (Thu Sep 27 11:34:45 2012)"

/* Lundtastic services */
