/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  2634
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.internal-gmo"
#define VERSION_DATE   "Wed Oct 22 16:20:37 2014"
#define VERSION_STRING "lundman@shinken.internal-gmo build 2634 (Wed Oct 22 16:20:37 2014)"

/* Lundtastic services */
